### ISSUE TITLE
"jekyll-theme-slate theme could not be found" when serving locally

### ISSUE THREAD

**Issue by arnemertz** [pages-themes/slate#64]
I am constantly getting the above error message when I try to serve the theme locally.

The steps I took: 
1. install Jekyll and create a new site according to https://jekyllrb.com/docs/
2. add the line `gem "github-pages", group: :jekyll_plugins` according to your README
3. update the github-pages gem (it's now at version 216 which seems to be the newest at this time)
4. remove the line `gem "jekyll", "~> 4.2.0"` from the Gemfile according to the surrounding comments
5. run bundle install and bundle update (did this multiple times to no avail)

Error message on `bundle exec jekyll serve`:

```
...
         3: from /home/amertz/gems/gems/jekyll-3.9.0/lib/jekyll/theme.rb:82:in `gemspec'
         2: from /usr/lib/ruby/2.7.0/rubygems/specification.rb:988:in `find_by_name'
         1: from /usr/lib/ruby/2.7.0/rubygems/dependency.rb:323:in `to_spec'
/usr/lib/ruby/2.7.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'jekyll-theme-slate' (>= 0) among 130 total gem(s) (Gem::MissingSpecError)
...
         4: from /home/amertz/gems/gems/jekyll-3.9.0/lib/jekyll/site.rb:439:in `new'
         3: from /home/amertz/gems/gems/jekyll-3.9.0/lib/jekyll/theme.rb:12:in `initialize'
         2: from /home/amertz/gems/gems/jekyll-3.9.0/lib/jekyll/theme.rb:19:in `root'
         1: from /home/amertz/gems/gems/jekyll-3.9.0/lib/jekyll/theme.rb:81:in `gemspec'
/home/amertz/gems/gems/jekyll-3.9.0/lib/jekyll/theme.rb:84:in `rescue in gemspec': The jekyll-theme-slate theme could not be found. (Jekyll::Errors::MissingDependencyException)
```

**Comment by rameezrehman408** [comment]
I am also having similar issue while using the theme Cayman ("jekyll-theme-cayman").
